# Generated by Django 3.2.6 on 2021-08-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='Supplier',
        ),
    ]
