# Generated by Django 3.2.6 on 2021-10-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonbase', '0002_alter_city_options'),
        ('rawmaterial', '0002_rename_suppliers_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonbase.city'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='adress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
