# Generated by Django 3.2.6 on 2021-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('community', models.CharField(max_length=100, null=True)),
                ('country', models.IntegerField(choices=[(1, 'France'), (2, 'Canada'), (3, 'United States')])),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
