# Generated by Django 3.2.6 on 2021-10-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
