# Generated by Django 3.2.8 on 2021-10-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterial', '0004_auto_20211025_1650'),
        ('commonbase', '0002_alter_city_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
